// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umxcxfnbspgcziiwkodf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVteGN4Zm5ic3BnY3ppaXdrb2RmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMzYwNTksImV4cCI6MjA3MDkxMjA1OX0.Uv89GTGZ3xxPxwmMyn5mbkOLLx4DjdLCAOhOVQyLVtw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});